services:
  oracle:
    extends:
      file: docker-compose.yml
      service: oracle

  keycloak:
    extends:
      file: docker-compose.yml
      service: keycloak

  puppet:
    extends:
      file: docker-compose.yml
      service: puppet

  calendar:
    extends:
      file: docker-compose.yml
      service: calendar
    build:
      context: .
      dockerfile: Dockerfile