
DROP SEQUENCE EVENT_ID;

CREATE SEQUENCE EVENT_ID;

DROP SEQUENCE OCCURRENCE_ID;

CREATE SEQUENCE OCCURRENCE_ID;

DROP SEQUENCE OCCURRENCE_STYLE_ID;

CREATE SEQUENCE OCCURRENCE_STYLE_ID;

DROP TABLE OCCURRENCE_STYLE CASCADE CONSTRAINTS PURGE;

DROP TABLE OCCURRENCE_STYLE_CHOICE CASCADE CONSTRAINTS PURGE;

DROP TABLE OCCURRENCE CASCADE CONSTRAINTS PURGE;

DROP TABLE EVENT CASCADE CONSTRAINTS PURGE;

DROP TABLE CALENDAR CASCADE CONSTRAINTS PURGE;

CREATE TABLE CALENDAR
(
	CALENDAR_ID          INTEGER NOT NULL ,
	NAME                 VARCHAR2(64 CHAR) NOT NULL ,
	ORDER_ID             INTEGER NOT NULL ,
	DESCRIPTION          VARCHAR2(256 CHAR) NULL ,
CONSTRAINT  CALENDAR_PK PRIMARY KEY (CALENDAR_ID)
);

CREATE TABLE EVENT
(
	EVENT_ID             INTEGER NOT NULL ,
	CALENDAR_ID          INTEGER NOT NULL ,
	TASK_ID              INTEGER NULL ,
CONSTRAINT  EVENT_PK PRIMARY KEY (EVENT_ID),
CONSTRAINT EVENT_FK2 FOREIGN KEY (CALENDAR_ID) REFERENCES CALENDAR (CALENDAR_ID) ON DELETE CASCADE
);

CREATE TABLE OCCURRENCE
(
	OCCURRENCE_ID        INTEGER NOT NULL ,
	YEAR_MONTH_DAY       TIMESTAMP(0) NOT NULL  CONSTRAINT  OCCURRENCE_CK1 CHECK (EXTRACT(HOUR FROM YEAR_MONTH_DAY) = 0 AND EXTRACT(MINUTE FROM YEAR_MONTH_DAY) = 0 AND EXTRACT(SECOND FROM YEAR_MONTH_DAY) = 0),
	SHIFT                VARCHAR2(5 CHAR) NOT NULL  CONSTRAINT  OCCURRENCE_CK2 CHECK (SHIFT IN ('OWL', 'DAY', 'SWING')),
	TITLE                VARCHAR2(128 CHAR) NOT NULL ,
	DESCRIPTION          VARCHAR2(512 CHAR) NULL ,
	LIAISON              VARCHAR2(64 CHAR) NULL ,
	DISPLAY              VARCHAR2(20 CHAR) NOT NULL  CONSTRAINT  OCCURRENCE_CK3 CHECK (DISPLAY IN ('SHOW', 'MORE', 'HIDE')),
	REMARK               VARCHAR2(512 CHAR) NULL ,
	EVENT_ID             INTEGER NOT NULL ,
	ORDER_ID             INTEGER NOT NULL  CONSTRAINT  OCCURRENCE_CK4 CHECK (ORDER_ID >= 1),
CONSTRAINT  OCCURRENCE_PK PRIMARY KEY (OCCURRENCE_ID),
CONSTRAINT OCCURRENCE_FK1 FOREIGN KEY (EVENT_ID) REFERENCES EVENT (EVENT_ID) ON DELETE CASCADE
);

CREATE TABLE OCCURRENCE_STYLE_CHOICE
(
	OCCURRENCE_STYLE_CHOICE_ID INTEGER NOT NULL ,
	NAME                 VARCHAR2(20 CHAR) NOT NULL ,
	CSS_CLASS_NAME       VARCHAR2(20 CHAR) NOT NULL ,
	ORDER_ID             INTEGER NOT NULL ,
CONSTRAINT  OCCURRENCE_STYLE_CHOICE_PK PRIMARY KEY (OCCURRENCE_STYLE_CHOICE_ID),CONSTRAINT  OCCURRENCE_STYLE_CHOICE_AK1 UNIQUE (NAME),CONSTRAINT  OCCURRENCE_STYLE_CHOICE_AK2 UNIQUE (CSS_CLASS_NAME),CONSTRAINT  OCCURRENCE_STYLE_CHOICE_AK3 UNIQUE (ORDER_ID)
);

CREATE TABLE OCCURRENCE_STYLE
(
	OCCURRENCE_SYLE_ID   INTEGER NOT NULL ,
	OCCURRENCE_ID        INTEGER NOT NULL ,
	OCCURRENCE_STYLE_CHOICE_ID INTEGER NOT NULL ,
CONSTRAINT  OCCURRENCE_STYLE_PK PRIMARY KEY (OCCURRENCE_SYLE_ID),CONSTRAINT  OCCURRENCE_STYLE_AK1 UNIQUE (OCCURRENCE_ID,OCCURRENCE_STYLE_CHOICE_ID),
CONSTRAINT OCCURRENCE_STYLE_FK1 FOREIGN KEY (OCCURRENCE_ID) REFERENCES OCCURRENCE (OCCURRENCE_ID) ON DELETE CASCADE,
CONSTRAINT OCCURRENCE_STYLE_FK2 FOREIGN KEY (OCCURRENCE_STYLE_CHOICE_ID) REFERENCES OCCURRENCE_STYLE_CHOICE (OCCURRENCE_STYLE_CHOICE_ID) ON DELETE SET NULL
);

-- Audit Tables
CREATE SEQUENCE HIBERNATE_SEQUENCE INCREMENT BY 1 START WITH 1;

CREATE TABLE CALENDAR_REVISION_INFO
(
    REV         NUMBER(10,0) NOT NULL,
    REVTSTMP    NUMBER(19,0) NOT NULL,
    USERNAME    VARCHAR2(64 CHAR),
    ADDRESS     VARCHAR2(64 CHAR),
    PRIMARY KEY (REV)
);

CREATE TABLE EVENT_AUD
(
    EVENT_ID             INTEGER NOT NULL ,
    REV                  NUMBER(10,0) NOT NULL ,
    REVTYPE              NUMBER(3,0) NOT NULL ,
    TASK_ID              INTEGER NULL ,
    CONSTRAINT EVENT_AUD_PK PRIMARY KEY (EVENT_ID, REV) ,
    CONSTRAINT EVENT_AUD_FK1 FOREIGN KEY (REV) REFERENCES CALENDAR_REVISION_INFO (REV) ON DELETE CASCADE
);

CREATE TABLE OCCURRENCE_AUD
(
    OCCURRENCE_ID        INTEGER NOT NULL ,
    REV                  NUMBER(10,0) NOT NULL ,
    REVTYPE              NUMBER(3,0) NOT NULL ,
    YEAR_MONTH_DAY       TIMESTAMP(0) NOT NULL ,
    SHIFT                VARCHAR2(5 CHAR) NOT NULL ,
    TITLE                VARCHAR2(128 CHAR) NOT NULL ,
    DESCRIPTION          VARCHAR2(512 CHAR) NULL ,
    LIAISON              VARCHAR2(64 CHAR) NULL ,
    REMARK               VARCHAR2(512 CHAR) NULL ,
    DISPLAY              VARCHAR2(20 CHAR) NOT NULL ,
    EVENT_ID             INTEGER NOT NULL ,
    ORDER_ID             INTEGER NOT NULL ,
    CONSTRAINT OCCURRENCE_AUD_PK PRIMARY KEY (OCCURRENCE_ID, REV) ,
    CONSTRAINT OCCURRENCE_AUD_FK1 FOREIGN KEY (REV) REFERENCES CALENDAR_REVISION_INFO (REV) ON DELETE CASCADE
);

CREATE TABLE OCCURRENCE_STYLE_AUD
(
    OCCURRENCE_STYLE_ID        INTEGER NOT NULL ,
    REV                        NUMBER(10,0) NOT NULL ,
    REVTYPE                    NUMBER(3,0) NOT NULL ,
    OCCURRENCE_ID              INTEGER NOT NULL ,
    OCCURRENCE_STYLE_CHOICE_ID INTEGER NOT NULL ,
    CONSTRAINT OCCURRENCE_STYLE_AUD_PK PRIMARY KEY (OCCURRENCE_STYLE_ID, REV) ,
    CONSTRAINT OCCURRENCE_STYLE_AUD_FK1 FOREIGN KEY (REV) REFERENCES CALENDAR_REVISION_INFO (REV) ON DELETE CASCADE
);

-- Populate Style Choices
insert into occurrence_style_choice values (1, 'Tentative Plan', 'tentative', 1);
insert into occurrence_style_choice values (2, 'Major Event', 'major', 2);
insert into occurrence_style_choice values (3, 'Incomplete Task', 'incomplete', 3);
insert into occurrence_style_choice values (4, 'Lock Up', 'lock', 4);
insert into occurrence_style_choice values (5, 'Utility Interruption', 'utility', 5);
insert into occurrence_style_choice values (6, 'Radcon Group', 'radcon', 6);
insert into occurrence_style_choice values (7, 'Special Support', 'support', 7);
insert into occurrence_style_choice values (8, 'Subset', 'subset', 8);
insert into occurrence_style_choice values (9, 'New/Changed', 'changed', 9);

--External References (not used anymore)
alter table Event add constraint EVENT_FK1 foreign key (task_id) references ATLIS7_OWNER.TASKS (id) on delete set null;
